CREATE TABLE user_course_data (
    user_id BIGINT,
    user_name TEXT,
    user_surname TEXT,
    user_email TEXT,
    user_role TEXT,
    user_external_id TEXT,
    course_id BIGINT,
    course_title TEXT,
    course_category TEXT,
    course_duration FLOAT,
    completion_ratio FLOAT,
    num_video_consumed_minutes FLOAT,
    course_enroll_date TIMESTAMP,
    course_start_date TIMESTAMP,
    course_completion_date TIMESTAMP,
    course_first_completion_date TIMESTAMP,
    course_last_accessed_date TIMESTAMP,
    last_activity_date DATE,
    is_assigned BOOLEAN,
    assigned_by TEXT,
    user_is_deactivated BOOLEAN,
    lms_user_id TEXT,
    CONSTRAINT user_course_unique UNIQUE (user_id, course_id)
);
